- name: Ensure absence of configuration
  file:
    state: absent
    dest: "{{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }}"

- name: Install galera
  yum: 
    name: "{{ item }}"
    enablerepo: mariadb   
    state: present
  with_items:
    - galera

- name: Add galera configuration
  template: 
    src:  mysqld_galera.j2 
    dest: "{{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }}"
    owner: "root" 
    group: "root" 
    mode: 0644
  notify:
    - restart mysql
    