- name: Ensure absence of configuration
  file:
    state: absent
    dest: "{{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }}"

- name: Install galera
  yum: 
    name: "{{ item }}"
    enablerepo: mariadb   
    state: present
  with_items:
    - galera

- name: Create Galera Admins
  mysql_user: 
    name: "{{ item.name }}" 
    login_unix_socket: "{{ mysql_socket }}/mysql.sock" 
    password: "{{ item.secrets }}" 
    state: present
    host: "{{ item.host }}"
    encrypted: yes
    priv: "{{ item.privileges }}"
  when: 
    - "mysql_install_galera_admins"
    - (item.host != "all")
  with_items: 
    - "{{ mysql_galera_admins }}"

- name: Create Galera Admins
  mysql_user: 
    name: "{{ item.name }}" 
    login_unix_socket: "{{ mysql_socket }}/mysql.sock" 
    password: "{{ item.secret }}" 
    state: present
    host: localhost
    encrypted: yes
    priv: "{{ item.privileges }}"
  when: 
    - "mysql_install_galera_admins"
    - (item.host == "all")
  with_items: 
    - "{{ mysql_galera_admins }}"

- name: Create Galera Admins
  mysql_user: 
    name: "{{ item.name }}" 
    login_unix_socket: "{{ mysql_socket }}/mysql.sock" 
    password: "{{ item.secret }}" 
    state: present
    host_all: yes
    encrypted: yes
    priv: "{{ item.privileges }}"
  when: 
    - "mysql_install_galera_admins}"
    - (item.host == "all")
  with_items: 
    - "{{ mysql_galera_admins }}"


- name: Add galera configuration
  template: 
    src:  mysqld_galera.j2 
    dest: "{{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }}"
    owner: "root" 
    group: "root" 
    mode: 0644
  notify:
    - restart galera
    