- name: Install MariaDB
  yum: 
    name: "{{ item }}"
    enablerepo: mariadb   
    state: present
  with_items:
    - galera
  when: "{{ mysql_galera_node }}"

- name: Add configuration
  template: 
    src:  mysqld_galera.j2 
    dest: "{{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }}"
    owner: "root" 
    group: "root" 
    mode: 0644
  notify:
    - restart mysql
    