---
- name: restart mysql
  systemd: 
    name: mysqld
    state: restarted
    enabled: yes
- name: stop mysql
  systemd: 
    name: mysqld 
    state: stopped
    enabled: yes
- name: disable mysql
  systemd: 
    name: mysqld
    state: stopped
    enabled: no
- name: start mysql
  systemd: 
    name: mysql 
    state: started
    enabled: yes
